"""Centralized Error Code Constants."""

from enum import StrEnum


class ErrorCode(StrEnum):
    """System-wide error code definitions for API error responses."""

    # Validation Errors
    ERR_INVALID_PAYLOAD = "ERR_INVALID_PAYLOAD"
    ERR_INVALID_MESSAGE_ID = "ERR_INVALID_MESSAGE_ID"
    ERR_INVALID_MEDIA = "ERR_INVALID_MEDIA"

    # Application Errors
    ERR_RESOURCE_NOT_FOUND = "ERR_RESOURCE_NOT_FOUND"
    ERR_UNAUTHORIZED = "ERR_UNAUTHORIZED"
    ERR_RATE_LIMIT_EXCEEDED = "ERR_RATE_LIMIT_EXCEEDED"

    # Infrastructure & Integration Errors
    ERR_DATABASE_FAILURE = "ERR_DATABASE_FAILURE"
    ERR_CACHE_FAILURE = "ERR_CACHE_FAILURE"
    ERR_LLM_TIMEOUT = "ERR_LLM_TIMEOUT"
    ERR_LLM_SERVICE_UNAVAILABLE = "ERR_LLM_SERVICE_UNAVAILABLE"
    ERR_META_WEBHOOK_VERIFICATION_FAILED = "ERR_META_WEBHOOK_VERIFICATION_FAILED"

    # System Errors
    ERR_INTERNAL_SERVER_ERROR = "ERR_INTERNAL_SERVER_ERROR"
