"""System-wide operational constants."""

CORRELATION_ID_HEADER = "X-Correlation-ID"
DEFAULT_TIMEZONE = "UTC"
MAX_AUDIO_DURATION_SECONDS = 300
MAX_IMAGE_SIZE_BYTES = 10 * 1024 * 1024  # 10MB
DEFAULT_TOP_K_RETRIEVAL = 5
